- name: install playbook
  hosts: all

  tasks:
    - name: install apache2 and mysql-server
      ansible.builtin.apt:
        update_cache: true
        name: "{{ item }}"
        state: absent
      loop:
        - apache2
        - mysql-server

    - name: gather package facts
      ansible.builtin.package_facts:
        manager: auto

    - name: copy index.html if apache2 is installed
      ansible.builtin.copy:
        content: "<h1>Bonjour</h1>"
        dest: /var/www/html/index.html
        mode: '0644'
      when: "'apache2' in ansible_facts.packages"
  

    
        

  